name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  install-and-build:
    strategy:
      fail-fast: false
      matrix:
        version: [18-static, 18-shared, 19-static, 19-shared]
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - run: opam repo add local ./repository
      - run: opam update
      - run: opam install llvm.${{ matrix.version }}
      - run: opam install dune
      - run: opam exec -- dune build ./test.exe --verbose
      - run: opam exec -- dune exec ./test.exe --verbose
      - run: opam exec -- dune build ./test.bc.exe --verbose
      - run: opam exec -- dune exec ./test.bc.exe --verbose
