name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build-static:
    strategy:
      fail-fast: false
      matrix:
        link_mode: [static, shared]
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - run: opam repo add local ./repository
      - run: opam update
      - run: opam install conf-llvm-${{ matrix.link_mode }}
      - run: opam install llvm.18-${{ matrix.link_mode }}
      - run: opam install dune
      - run: dune build ./test.exe --verbose
      - run: dune exec ./test.exe --verbose
      - run: dune build ./test.bc --verbose
      - run: dune exec ./test.bc --verbose
